default['ruby-env']['user'] = 'vagrant'
default['ruby-env']['group'] = 'vagrant'
default['ruby-env']['version'] = '2.1.2'
default['ruby-env']['rbenv_url'] = 'https://github.com/sstephenson/rbenv.git'
default['ruby-env']['ruby-build_url'] = 'https://github.com/sstephenson/ruby-build.git'
default['ruby-env']['rbenv-default-gems_url'] = 'https://github.com/sstephenson/rbenv-default-gems.git'
default['ruby-env']['rbenv-gem-rehash_url'] = 'https://github.com/sstephenson/rbenv-gem-rehash.git'
